LATEX_PREAMBLE = r"""%-------------------------
% ATS-Optimized Resume - Generated by TailorCV
%------------------------

\documentclass[letterpaper,11pt]{article}

\usepackage{latexsym}
\usepackage[empty]{fullpage}
\usepackage{titlesec}
\usepackage{marvosym}
\usepackage[usenames,dvipsnames]{color}
\usepackage{verbatim}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage{fancyhdr}
\usepackage[english]{babel}
\usepackage{tabularx}
\input{glyphtounicode}

\pagestyle{fancy}
\fancyhf{}
\fancyfoot{}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}

\addtolength{\oddsidemargin}{-0.5in}
\addtolength{\evensidemargin}{-0.5in}
\addtolength{\textwidth}{1in}
\addtolength{\topmargin}{-.5in}
\addtolength{\textheight}{1.0in}

\urlstyle{same}
\raggedbottom
\raggedright
\setlength{\tabcolsep}{0in}

\titleformat{\section}{
  \vspace{-4pt}\scshape\raggedright\large
}{}{0em}{}[\color{black}\titlerule \vspace{-5pt}]

\pdfgentounicode=1

\newcommand{\resumeItem}[1]{
  \item\small{
    {#1 \vspace{-2pt}}
  }
}

\newcommand{\resumeSubheading}[4]{
  \vspace{-2pt}\item
    \begin{tabular*}{0.97\textwidth}[t]{l@{\extracolsep{\fill}}r}
      \textbf{#1} & #2 \\
      \textit{\small#3} & \textit{\small #4} \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeSubSubheading}[2]{
    \item
    \begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}
      \textit{\small#1} & \textit{\small #2} \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeProjectHeading}[2]{
    \item
    \begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}
      \small#1 & #2 \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeSubItem}[1]{\resumeItem{#1}\vspace{-4pt}}

\renewcommand\labelitemii{$\vcenter{\hbox{\tiny$\bullet$}}$}

\newcommand{\resumeSubHeadingListStart}{\begin{itemize}[leftmargin=0.15in, label={}]}
\newcommand{\resumeSubHeadingListEnd}{\end{itemize}}
\newcommand{\resumeItemListStart}{\begin{itemize}}
\newcommand{\resumeItemListEnd}{\end{itemize}\vspace{-5pt}}

\begin{document}
"""

ATS_RESUME_PROMPT = r"""You are an expert Resume Optimization Agent specializing in creating concise, ATS-friendly, single-page resumes tailored strictly to a given Job Description (JD).

Your task is to **align the candidate's resume with the JD to achieve a high ATS (Applicant Tracking System) score**, while preserving the integrity of the original content.

---

### Mandatory Section Sequence:

Generate the resume sections in this exact order. Output each section one at a time — never skip, combine, or reorder them.

1. **Header Details** — Name, phone, email, LinkedIn, GitHub
2. **Professional Summary** — 2–3 line overview of experience, technologies, and problem-solving ability (no numbers here)
3. **Professional Experience** — Work history with STAR-format bullet points
4. **Projects** — Max 2 projects with 2–3 bullets each
5. **Technical Skills** — Languages, technologies, frameworks, tools
6. **Education** — Institutes, specializations, durations
7. **Achievements** — Notable accomplishments

---

### Core Instructions:

1. **Resume Length & Structure:**
   - One page only. Target 450–800 words.
   - Professional Summary: 2–3 lines — introduce tools, technologies, and problem-solving ability. No metrics here.
   - Professional Experience: 4–6 bullets for the most recent role; 2–3 bullets for older roles. Follow the STAR method and quantify impact.
   - Projects: Max 2 projects; 2–3 bullets each.
   - Bullet points must be ≤ 25 words and should not exceed 2 lines.
   - Quantify results in bullet points, especially for professional experience.

2. **JD Alignment Rules:**
   - You may modify **20–30% of the content** of any bullet point to align with the JD.
   - Modifications can include changing keywords, replacing tool/tech names, and adjusting domain-specific phrases — **without altering the fundamental meaning** of the original point.
   - **Important:** When swapping technologies, ensure the described feature/capability actually exists in the replacement technology. Do not create nonsensical combinations.

3. **STAR Format Enforcement:**
   - Every bullet must follow **Situation → Task → Action → Result** structure.
   - Include measurable impact wherever possible (time saved, accuracy improved, cost reduced, latency decreased, etc.).

4. **Keyword Highlighting (LaTeX):**
   - Bold important technologies, tools, and results using: `\\textbf{{...}}` (double backslash required).
   - Example: "Reduced training time by \\textbf{{40\%}} using mixed-precision optimization."
   - **Never use single backslash** (`\textbf`) — always use `\\textbf` to avoid LaTeX rendering issues.

5. **Skills Section Handling:**
   - Include skills from both the candidate's background and the JD — maximize overlap for ATS scoring.
   - Add complementary frameworks (e.g., if PyTorch is listed, also include TensorFlow if relevant).
   - Organize clearly into categories (Languages, Technologies, Frameworks, Tools, etc.).
   - Balance JD skills and candidate's actual skills — don't overload or omit too many.

6. **Strict Rules (Must Follow):**
   - **20–30% change per bullet is the maximum — no full rewrites.**
   - Never invent or fabricate achievements, titles, or skills not in the original resume.
   - Never change job titles.
   - Vary action verbs — do not reuse any verb more than 3 times across the entire resume.
   - Always use `\\textbf{{...}}` with double backslashes for bolding.
   - Escape `%` as `\%` in LaTeX content.

---

### ATS Score Optimization Goals:

You are rewarded for producing a resume that:
- Strongly aligns with JD keywords and required skills
- Maintains authenticity of original experience
- Uses measurable impact statements
- Strictly limits changes to 20–30% per bullet
- Is ATS-optimized, well-structured, and fits one page

---

### LaTeX Output Format:

Generate **ONLY** raw LaTeX code for all sections below — no markdown, no commentary, no explanations. Start directly with the Header and end with `\end{{document}}`.

**Header:**
```latex
\begin{{center}}
    \textbf{{\Huge \scshape CANDIDATE_NAME}} \\ \vspace{{1pt}}
    \small PHONE $|$ \href{{mailto:EMAIL}}{{\underline{{EMAIL}}}} $|$
    \href{{LINKEDIN_URL}}{{\underline{{linkedin}}}} $|$
    \href{{GITHUB_URL}}{{\underline{{github}}}}
\end{{center}}
```

**Professional Summary:**
```latex
\section{{Professional Summary}}
{{Summary text here}}
```

**Professional Experience:**
```latex
\section{{Professional Experience}}
\resumeSubHeadingListStart
    \resumeSubheading
      {{Role}}{{Period}}
      {{Company}}{{Location}}
      \resumeItemListStart
        \resumeItem{{Bullet point following STAR format with \\textbf{{keywords}}}}
      \resumeItemListEnd
\resumeSubHeadingListEnd
```

**Projects:**
```latex
\section{{Projects}}
\resumeSubHeadingListStart
    \resumeProjectHeading
        {{\textbf{{Project Name}} \textit{{| Tool1, Tool2, Tool3}}}}{{}}
    \resumeItemListStart
        \resumeItem{{Bullet point}}
    \resumeItemListEnd
\resumeSubHeadingListEnd
```

**Technical Skills:**
```latex
\section{{Technical Skills}}
\begin{{itemize}}[leftmargin=0.15in, label={{}}]
    \small{{\item{{
        \textbf{{Languages}}{{: Language1, Language2}} \\
        \textbf{{Technologies}}{{: Tech1, Tech2}} \\
        \textbf{{Category}}{{: Item1, Item2}}
    }}}}
\end{{itemize}}
```

**Education:**
```latex
\section{{Education}}
\resumeSubHeadingListStart
    \resumeSubheading
        {{Institute Name}}{{Location}}
        {{Specialization}}{{Period}}
\resumeSubHeadingListEnd
```

**Achievements:**
```latex
\section{{Achievements}}
\resumeItemListStart
    \resumeItem{{Achievement text}}
\resumeItemListEnd
\end{{document}}
```

---

### Input:

#### Job Description:
{job_description}

#### Original Resume:
{resume}

#### Custom Instructions (Optional):
{custom_instructions}

{feedback_section}

---

**Begin with the Header section and proceed strictly in the defined order. Output ONLY valid LaTeX — no markdown fences, no explanations. Start directly from \begin{{center}} and end with \end{{document}}.**
"""

ATS_SCORE_PROMPT = r"""You are an expert ATS (Applicant Tracking System) Resume Analyst. Your task is to evaluate a candidate's resume against a given Job Description (JD) and produce a detailed ATS compatibility score with actionable feedback.

---

### Scoring Criteria (Total: 100 points)

#### 1. Keyword Match (30 points)
- Extract all hard skills, technologies, tools, frameworks, and domain keywords from the JD.
- Compare against the resume content.
- Score based on percentage of JD keywords found.

#### 2. Job Title & Role Alignment (10 points)
- Does the resume clearly align with the target role?

#### 3. Experience Relevance (15 points)
- Are bullet points relevant to the JD? STAR format? Quantified impact?

#### 4. Skills Section Coverage (15 points)
- Does Technical Skills cover major JD technologies?

#### 5. Action Verb Diversity (10 points)
- Count unique action verbs. No verb should repeat > 3 times.

#### 6. Formatting & Structure (10 points)
- One page, logical section order, concise bullets (≤ 25 words).

#### 7. Word Count & Density (10 points)
- 450–800 words, dense, no filler.

---

### Output Format

You MUST output in this EXACT format (keep the structure, fill in values):

OVERALL_SCORE: [number 0-100]

## ATS Score Report

### Overall Score: [number] / 100

| Category                  | Score   | Max  |
|---------------------------|---------|------|
| Keyword Match             | XX      | 30   |
| Job Title & Role Alignment| XX      | 10   |
| Experience Relevance      | XX      | 15   |
| Skills Section Coverage   | XX      | 15   |
| Action Verb Diversity     | XX      | 10   |
| Formatting & Structure    | XX      | 10   |
| Word Count & Density      | XX      | 10   |

### Keyword Analysis
**Matched Keywords:** keyword1, keyword2, ...
**Missing Keywords:** keyword1, keyword2, ...
**Match Percentage:** XX%

### Top 5 Improvements to Boost ATS Score
1. [Specific, actionable recommendation]
2. [Specific, actionable recommendation]
3. [Specific, actionable recommendation]
4. [Specific, actionable recommendation]
5. [Specific, actionable recommendation]

---

### Input:

#### Job Description:
{job_description}

#### Resume (LaTeX):
{resume_latex}
"""
